doc-warnings: no # experimental, raises an exception
test-warnings: no
strictness: veryhigh
max-line-length: 160
# We don't use any of the auto-detected things, and
# auto-detection slows down startup
autodetect: false
requirements:
    - requirements.txt

python-targets:
  - 3
ignore-paths:
  - docs/
  - build/
  - dist/
  - travis/
  - tests/
  - .eggs

ignore-patterns:
  # disabled code
  - ^src/greentest/xtest_.*py
  # standard library code
  - ^src/greentest/2.*
  - ^src/greentest/3.*
  # benchmarks that aren't used/changed much
  - ^src/greentest/bench_.*py

pyroma:
  run: true

mccabe:
  # We have way too many violations of the complexity measure.
  # We should enable this and fix them one at a time, but that's
  # more refactoring than I want to do initially.
  run: true


