language: python
python:
  - "3.5"
  - "3.6"

install:
  - python3 -m pip install requests
  - python3 -m pip install pyjwt
  - python3 setup.py install

# command to run tests
script: 
  - cd tests
  - python -m unittest pair_tests.py
  - python -m unittest api_tests.py
  - python -m unittest interface_tests.py


branches:
  only:
  - master
  - dev