language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install bitex


# command to run tests
script:
  - pylint --rcfile=pylint.rc bitex
  - pycodestyle --max-line-length=100 bitex
  - pydocstyle bitex
  - cd tests
  - python api.py
  - python formatters.py



branches:
  only:
  - master
  - dev
