language: python
python:
  - "3.5"
  - "3.6"

# command to run tests
script: echo "Running.."

install:
  - pip --version
  - pip install coverage twine

script: echo "Starting.."

jobs:
  include:
    - stage: lint
      script: bash ./travis/execute_linters.sh
    - stage: compile
      script: python setup.py install
    - stage: test
      script:  bash ./travis/execute_tests.sh
    - stage: deploy
      provider: pypi
      user: $PYPI_NAME
      password: $PYPI_PW
      on:
        tags: true
        branch: master

stages:
  - lint
  - compile
  - test
  - name: deploy
    if: branch = master


branches:
  only:
  - release-2.0.0