language: python

python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

jobs:
  include:
    - stage: lint
      python: 3.6
      script:
        - pip install pylint
        - pylint --rcfile=pylint.rc bitex
      script:
        - pip install pydocstyle
        - pydocstyle bitex
      script:
        - pip install pycodestyle
        - pycodestyle --max-line-length=100 bitex
    - stage: compile
      python: 3.5
      script: python setup.py install
    - stage: test
      script:
        - pip install coverage coveralls
        - coverage run --source=bitex setup.py test
      after_success: coveralls
    - stage: deploy
      script: skip
      provider: pypi
      user: $PYPI_NAME
      password: $PYPI_PW

stages:
  - lint
  - compile
  - test
  - name: deploy
    if: tag IS present

allow_failures:
  python:
    - "3.0"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"

branches:
  only:
  - master
  - dev