language: python
python:
  - "3.5"
  - "3.6"

install:
  - python3 -m pip install requests
  - python3 -m pip install pyjwt
  - python3 -m pip install pylint pycodestyle pydocstyle
  - python3 setup.py install

# command to run tests
jobs:
  include:
    - stage: Linter Checks
      script: pylint --rcfile=pylint.rc bitex
    -
      script: pycodestyle --max-line-length=100 bitex
    -
      script: pydocstyle bitex

    - stage: Unit-tests
      script: cd tests && python -m unittest api.py
    - 
      script: cd tests && python -m unittest formatters.py

    - stage: Deploy
      script: echo "Skipping deployment."
      
branches:
  only:
  - release-2.0.0
