language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install btfxwss


# command to run tests
script:
  - cd tests
  - python api.py
  - python formatters.py



branches:
  only:
  - master
  - dev
