language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install bitex coverage coveralls


# command to run tests
script:
  - coverage run --source=bitex setup.py test
  - coveralls



branches:
  only:
  - master
