language: python
python:
  - "3.5"
  - "3.6"

install:
  - python3 -m pip install requests
  - python3 -m pip install pyjwt
  - python3 -m pip install pylint
  - python3 -m pip install pydocstyle
  - python3 -m pip install pycodestyle
  - python3 setup.py install

# command to run tests
script:
  - pylint --rcfile=pylint.rc bitex
  - pycodestyle --max-line-length=100 bitex
  - pydocstyle bitex
  - cd tests
  - python api.py
  - python formatters.py

      
branches:
  only:
  - release-2.0.0

